/*
Navicat SQLite Data Transfer

Source Server         : mai
Source Server Version : 31202
Source Host           : :0

Target Server Type    : SQLite
Target Server Version : 31202
File Encoding         : 65001

Date: 2016-07-12 11:55:57
*/

PRAGMA foreign_keys = OFF;

-- ----------------------------
-- Table structure for Countrys
-- ----------------------------
DROP TABLE IF EXISTS "main"."Countrys";
CREATE TABLE [Countrys] (
    [ID] text PRIMARY KEY NOT NULL,
    [EnName] text NOT NULL,
    [CnName] text NOT NULL,
    [EnShorting] text NOT NULL
);

-- ----------------------------
-- Records of Countrys
-- ----------------------------
INSERT INTO "main"."Countrys" VALUES (1, 'AFGHANISTAN', '阿富汗', 'AF');
INSERT INTO "main"."Countrys" VALUES (10, 'ARMENIA', '亚美尼亚', 'AM');
INSERT INTO "main"."Countrys" VALUES (100, 'GUYANA', '圭亚那', 'GY');
INSERT INTO "main"."Countrys" VALUES (101, 'HAITI', '海地', 'HT');
INSERT INTO "main"."Countrys" VALUES (102, 'HEARD ISLAND AND MCDONALD ISLANDS', '赫德岛和麦克唐岛', 'HM');
INSERT INTO "main"."Countrys" VALUES (103, 'HONDURAS', '洪都拉斯', 'HN');
INSERT INTO "main"."Countrys" VALUES (104, 'HONG KONG', '香港', 'HK');
INSERT INTO "main"."Countrys" VALUES (105, 'HUNGARY', '匈牙利', 'HU');
INSERT INTO "main"."Countrys" VALUES (106, 'ICELAND', '冰岛', 'IS');
INSERT INTO "main"."Countrys" VALUES (107, 'INDIA', '印度', 'IN');
INSERT INTO "main"."Countrys" VALUES (108, 'INDONESIA', '印度尼西亚', 'ID');
INSERT INTO "main"."Countrys" VALUES (109, 'IRAN', '伊朗', 'IR');
INSERT INTO "main"."Countrys" VALUES (11, 'ARUBA', '亚鲁巴', 'AW');
INSERT INTO "main"."Countrys" VALUES (110, 'IRAQ', '伊拉克', 'IQ');
INSERT INTO "main"."Countrys" VALUES (111, 'IRELAND', '爱尔兰', 'IE');
INSERT INTO "main"."Countrys" VALUES (112, 'ISRAEL', '以色列', 'IL');
INSERT INTO "main"."Countrys" VALUES (113, 'ITALY', '意大利', 'IT');
INSERT INTO "main"."Countrys" VALUES (114, 'JAMAICA', '牙买加', 'JM');
INSERT INTO "main"."Countrys" VALUES (115, 'JAPAN', '日本', 'JP');
INSERT INTO "main"."Countrys" VALUES (116, 'JORDAN', '约旦', 'JO');
INSERT INTO "main"."Countrys" VALUES (117, 'KAZAKHSTAN', '哈萨克斯坦', 'KZ');
INSERT INTO "main"."Countrys" VALUES (118, 'KENYA', '肯尼亚', 'KE');
INSERT INTO "main"."Countrys" VALUES (119, 'KIRIBATI', '基里巴斯', 'KI');
INSERT INTO "main"."Countrys" VALUES (12, 'ASCENSION', '阿森送', 'XD');
INSERT INTO "main"."Countrys" VALUES (120, 'KOREA DEMOCRATIC PEOPLE REPUBLIC OF', '朝鲜', 'KP');
INSERT INTO "main"."Countrys" VALUES (121, 'KOREA REPUBLIC OF', '韩国', 'KR');
INSERT INTO "main"."Countrys" VALUES (122, 'KUWAIT', '科威特', 'KW');
INSERT INTO "main"."Countrys" VALUES (123, 'KYRGYZSTAN', '吉尔吉斯斯坦', 'KG');
INSERT INTO "main"."Countrys" VALUES (124, 'LAO PEOPLE DEMOCRATIC REPUBLIC', '老挝', 'LA');
INSERT INTO "main"."Countrys" VALUES (125, 'LATVIA', '拉脱维亚', 'LV');
INSERT INTO "main"."Countrys" VALUES (126, 'LEBANON', '黎巴嫩', 'LB');
INSERT INTO "main"."Countrys" VALUES (127, 'LESOTHO', '莱索托', 'LS');
INSERT INTO "main"."Countrys" VALUES (128, 'LIBERIA', '科比里亚', 'LR');
INSERT INTO "main"."Countrys" VALUES (129, 'LIBYAN ARAB JAMAHIRIYA', '利比亚', 'LY');
INSERT INTO "main"."Countrys" VALUES (13, 'AUSTRALIA', '澳大利亚', 'AU');
INSERT INTO "main"."Countrys" VALUES (130, 'LIECHTENSTEIN', '列支敦士登', 'LI');
INSERT INTO "main"."Countrys" VALUES (131, 'LITHUANIA', '立陶宛', 'LT');
INSERT INTO "main"."Countrys" VALUES (132, 'LUXEMBOURG', '卢森堡', 'LU');
INSERT INTO "main"."Countrys" VALUES (133, 'MACAU', '澳门', 'MO');
INSERT INTO "main"."Countrys" VALUES (134, 'MACEDONIA ', '马其顿', 'MK');
INSERT INTO "main"."Countrys" VALUES (135, 'MADAGASCAR', '马达加斯加', 'MG');
INSERT INTO "main"."Countrys" VALUES (136, 'MADEIRA', '马德拉', 'XI');
INSERT INTO "main"."Countrys" VALUES (137, 'MALAWI', '马拉维', 'MW');
INSERT INTO "main"."Countrys" VALUES (138, 'MALAYSIA', '马来西亚', 'MY');
INSERT INTO "main"."Countrys" VALUES (139, 'MALDIVES', '马尔代夫', 'MV');
INSERT INTO "main"."Countrys" VALUES (14, 'AUSTRIA', '奥地利', 'AT');
INSERT INTO "main"."Countrys" VALUES (140, 'MALI', '马里', 'ML');
INSERT INTO "main"."Countrys" VALUES (141, 'MALTA', '马耳他', 'MT');
INSERT INTO "main"."Countrys" VALUES (142, 'MARIANA ISLANDS ', '马里亚纳群岛', 'MP');
INSERT INTO "main"."Countrys" VALUES (143, 'MARSHALL ISLANDS', '马绍尔群岛', 'MH');
INSERT INTO "main"."Countrys" VALUES (144, 'MARTINIQUE', '马提尼克岛', 'MQ');
INSERT INTO "main"."Countrys" VALUES (145, 'MAURITANIA', '毛里塔尼亚', 'MR');
INSERT INTO "main"."Countrys" VALUES (146, 'MAURITIUS', '毛里求斯', 'MU');
INSERT INTO "main"."Countrys" VALUES (147, 'MAYOTTE', '马约特', 'YT');
INSERT INTO "main"."Countrys" VALUES (148, 'MEXICO', '墨西哥', 'MX');
INSERT INTO "main"."Countrys" VALUES (149, 'MICRONESIA ', '密克罗尼西亚', 'FM');
INSERT INTO "main"."Countrys" VALUES (15, 'AZERBAIJAN', '阿塞拜疆', 'AZ');
INSERT INTO "main"."Countrys" VALUES (150, 'MOLDOVA REPUBLIC OF', '摩尔多瓦', 'MD');
INSERT INTO "main"."Countrys" VALUES (151, 'MONACO', '摩纳哥', 'MC');
INSERT INTO "main"."Countrys" VALUES (152, 'MONGOLIA', '蒙古', 'MN');
INSERT INTO "main"."Countrys" VALUES (153, 'MONTENEGRO', '黑山共和国', 'ME');
INSERT INTO "main"."Countrys" VALUES (154, 'MONTSERRAT', '蒙特塞拉特', 'MS');
INSERT INTO "main"."Countrys" VALUES (155, 'MOROCCO', '摩洛哥', 'MA');
INSERT INTO "main"."Countrys" VALUES (156, 'MOZAMBIQUE', '莫桑比克', 'MZ');
INSERT INTO "main"."Countrys" VALUES (157, 'MYANMAR', '缅甸', 'MM');
INSERT INTO "main"."Countrys" VALUES (158, 'NAMIBIA', '纳米比亚', 'NA');
INSERT INTO "main"."Countrys" VALUES (159, 'NAURU', '瑙鲁', 'NR');
INSERT INTO "main"."Countrys" VALUES (16, 'AZORES', '亚速尔', 'XH');
INSERT INTO "main"."Countrys" VALUES (160, 'NEPAL', '尼泊尔', 'NP');
INSERT INTO "main"."Countrys" VALUES (161, 'NETHERLANDS', '荷兰', 'NL');
INSERT INTO "main"."Countrys" VALUES (162, 'NETHERLANDS ANTILLES', '荷属安的列斯群岛', 'AN');
INSERT INTO "main"."Countrys" VALUES (163, 'NEW CALEDONIA', '新喀里多尼亚', 'NC');
INSERT INTO "main"."Countrys" VALUES (164, 'NEW ZEALAND', '新西兰', 'NZ');
INSERT INTO "main"."Countrys" VALUES (165, 'NEW ZEALAND ISLANDS TERRITORIES', '新西兰属土岛屿', 'XL');
INSERT INTO "main"."Countrys" VALUES (166, 'NICARAGUA', '尼加拉瓜', 'NI');
INSERT INTO "main"."Countrys" VALUES (167, 'NIGER', '尼日尔', 'NE');
INSERT INTO "main"."Countrys" VALUES (168, 'NIGERIA', '尼日利亚', 'NG');
INSERT INTO "main"."Countrys" VALUES (169, 'NIUE', '纽埃', 'NU');
INSERT INTO "main"."Countrys" VALUES (17, 'BAHAMAS', '巴哈马', 'BS');
INSERT INTO "main"."Countrys" VALUES (170, 'NORFOLK ISLAND', '诺福克岛', 'NF');
INSERT INTO "main"."Countrys" VALUES (171, 'NORWAY', '挪威', 'NO');
INSERT INTO "main"."Countrys" VALUES (172, 'OMAN', '阿曼', 'OM');
INSERT INTO "main"."Countrys" VALUES (173, 'PAKISTAN', '巴基斯坦', 'PK');
INSERT INTO "main"."Countrys" VALUES (174, 'PANAMA', '巴拿马', 'PA');
INSERT INTO "main"."Countrys" VALUES (175, 'PAPUA NEW GUINEA', '巴布亚新几内亚', 'PG');
INSERT INTO "main"."Countrys" VALUES (176, 'PARAGUAY', '巴拉圭', 'PY');
INSERT INTO "main"."Countrys" VALUES (177, 'PERU', '秘鲁', 'PE');
INSERT INTO "main"."Countrys" VALUES (178, 'PHILIPPINES', '菲律宾', 'PH');
INSERT INTO "main"."Countrys" VALUES (179, 'PITCAIRN', '皮特凯恩岛', 'PN');
INSERT INTO "main"."Countrys" VALUES (18, 'BAHRAIN', '巴林', 'BH');
INSERT INTO "main"."Countrys" VALUES (180, 'POLAND', '波兰', 'PL');
INSERT INTO "main"."Countrys" VALUES (181, 'PORTUGAL', '葡萄牙', 'PT');
INSERT INTO "main"."Countrys" VALUES (182, 'PUERTO RICO', '波多黎各', 'PR');
INSERT INTO "main"."Countrys" VALUES (183, 'QATAR', '卡塔尔', 'QA');
INSERT INTO "main"."Countrys" VALUES (184, 'REUNION', '留尼汪岛', 'RE');
INSERT INTO "main"."Countrys" VALUES (185, 'ROMANIA', '罗马尼亚', 'RO');
INSERT INTO "main"."Countrys" VALUES (186, 'RUSSIAN FEDERATION', '俄罗斯', 'RU');
INSERT INTO "main"."Countrys" VALUES (187, 'RWANDA', '卢旺达', 'RW');
INSERT INTO "main"."Countrys" VALUES (188, 'SAINT HELENA', '圣赫勒拿岛', 'SH');
INSERT INTO "main"."Countrys" VALUES (189, 'SAINT KITTS AND NEVIS', '圣基茨和尼维斯', 'KN');
INSERT INTO "main"."Countrys" VALUES (19, 'BALEARIC ISLANDS', '巴利阿里群岛', 'XJ');
INSERT INTO "main"."Countrys" VALUES (190, 'SAINT LUCIA', '圣卢西亚', 'LC');
INSERT INTO "main"."Countrys" VALUES (191, 'SAINT PIERRE AND MIQUELON', '圣皮埃尔和密克隆群岛', 'PM');
INSERT INTO "main"."Countrys" VALUES (192, 'SAINT VINCENT AND THE GRENADINES', '圣文森特和格林纳丁斯', 'VC');
INSERT INTO "main"."Countrys" VALUES (193, 'SAMOA USA TERRITORY', '萨摩亚', 'AS');
INSERT INTO "main"."Countrys" VALUES (194, 'SAMOA WESTERN', '西萨摩亚', 'WS');
INSERT INTO "main"."Countrys" VALUES (195, 'SAN MARINO', '圣马力诺', 'SM');
INSERT INTO "main"."Countrys" VALUES (196, 'SAO TOME AND PRINCIPE', '圣多美和普林西比', 'ST');
INSERT INTO "main"."Countrys" VALUES (197, 'SAUDI ARABIA', '沙特阿拉伯', 'SA');
INSERT INTO "main"."Countrys" VALUES (198, 'SENEGAL', '赛内加尔', 'SN');
INSERT INTO "main"."Countrys" VALUES (199, 'SERBIA', '塞尔维亚', 'RS');
INSERT INTO "main"."Countrys" VALUES (2, 'ALBANIA', '阿尔巴尼亚', 'AL');
INSERT INTO "main"."Countrys" VALUES (20, 'BANGLADESH', '孟加拉', 'BD');
INSERT INTO "main"."Countrys" VALUES (200, 'SEYCHELLES', '塞舌尔', 'SC');
INSERT INTO "main"."Countrys" VALUES (201, 'SIERRA LEONE', '塞拉里昂', 'SL');
INSERT INTO "main"."Countrys" VALUES (202, 'SINGAPORE', '新加坡', 'SG');
INSERT INTO "main"."Countrys" VALUES (203, 'SLOVAK REPUBLIC', '斯洛伐克', 'SK');
INSERT INTO "main"."Countrys" VALUES (204, 'SLOVENIA', '斯洛文尼亚', 'SI');
INSERT INTO "main"."Countrys" VALUES (205, 'SOLOMON ISLANDS', '所罗门群岛', 'SB');
INSERT INTO "main"."Countrys" VALUES (206, 'SOMALIA', '索马里', 'SO');
INSERT INTO "main"."Countrys" VALUES (207, 'SOUTH AFRICA', '南非', 'ZA');
INSERT INTO "main"."Countrys" VALUES (208, 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISL', '南乔治亚岛和南桑德韦奇岛', 'GS');
INSERT INTO "main"."Countrys" VALUES (209, 'SPAIN', '西班牙', 'ES');
INSERT INTO "main"."Countrys" VALUES (21, 'BARBADOS', '巴巴多斯', 'BB');
INSERT INTO "main"."Countrys" VALUES (210, 'SPANISH TERRITORIES OF N. AFRICA', '北非西班牙属土', 'XG');
INSERT INTO "main"."Countrys" VALUES (211, 'SPITSBERGEN', '斯匹次卑尔根群岛', 'SJ');
INSERT INTO "main"."Countrys" VALUES (212, 'SRI LANKA', '斯里兰卡', 'LK');
INSERT INTO "main"."Countrys" VALUES (213, 'SUDAN', '苏丹', 'SD');
INSERT INTO "main"."Countrys" VALUES (214, 'SURINAME', '苏里南', 'SR');
INSERT INTO "main"."Countrys" VALUES (215, 'SWAZILAND', '斯威士兰', 'SZ');
INSERT INTO "main"."Countrys" VALUES (216, 'SWEDEN', '瑞典', 'SE');
INSERT INTO "main"."Countrys" VALUES (217, 'SWITZERLAND', '瑞士', 'CH');
INSERT INTO "main"."Countrys" VALUES (218, 'SYRIAN ARAB REPUBLIC', '叙利亚', 'SY');
INSERT INTO "main"."Countrys" VALUES (219, 'TAIWAN', '台湾', 'TW');
INSERT INTO "main"."Countrys" VALUES (22, 'BELARUS', '白俄罗斯', 'BY');
INSERT INTO "main"."Countrys" VALUES (220, 'TAJIKISTAN', '塔吉克', 'TJ');
INSERT INTO "main"."Countrys" VALUES (221, 'TANZANIA', '坦桑尼亚', 'TZ');
INSERT INTO "main"."Countrys" VALUES (222, 'THAILAND', '泰国', 'TH');
INSERT INTO "main"."Countrys" VALUES (223, 'TOGO', '多哥', 'TG');
INSERT INTO "main"."Countrys" VALUES (224, 'TOKELAU', '托克劳', 'TK');
INSERT INTO "main"."Countrys" VALUES (225, 'TONGA', '汤加', 'TO');
INSERT INTO "main"."Countrys" VALUES (226, 'TORTOLA', '托儿托拉岛', 'VG');
INSERT INTO "main"."Countrys" VALUES (227, 'TRINIDAD AND TOBAGO', '千里达和多巴哥', 'TT');
INSERT INTO "main"."Countrys" VALUES (228, 'TRISTAN DA CUNHA', '特里斯坦', 'XB');
INSERT INTO "main"."Countrys" VALUES (229, 'TUNISIA', '突尼斯', 'TN');
INSERT INTO "main"."Countrys" VALUES (23, 'BELGIUM', '比利时', 'BE');
INSERT INTO "main"."Countrys" VALUES (230, 'TURKEY', '土耳其', 'TR');
INSERT INTO "main"."Countrys" VALUES (231, 'TURKMENISTAN', '土库曼', 'TM');
INSERT INTO "main"."Countrys" VALUES (232, 'TURKS AND CAICOS ISLANDS', '特克斯和凯科斯群岛', 'TC');
INSERT INTO "main"."Countrys" VALUES (233, 'TUVALU', '图瓦卢', 'TV');
INSERT INTO "main"."Countrys" VALUES (234, 'UGANDA', '乌干达', 'UG');
INSERT INTO "main"."Countrys" VALUES (235, 'UKRAINE', '乌克兰', 'UA');
INSERT INTO "main"."Countrys" VALUES (236, 'UNITED ARAB EMIRATES', '阿拉伯联合酋长国', 'AE');
INSERT INTO "main"."Countrys" VALUES (237, 'UNITED KINGDOM', '英国', 'GB');
INSERT INTO "main"."Countrys" VALUES (238, 'UNITED STATES', '美国', 'US');
INSERT INTO "main"."Countrys" VALUES (239, 'UNITED STATES MINOR OUTLYING ISLANDS', '美国本土外小岛屿', 'UM');
INSERT INTO "main"."Countrys" VALUES (24, 'BELIZE', '伯利兹', 'BZ');
INSERT INTO "main"."Countrys" VALUES (240, 'URUGUAY', '乌拉圭', 'UY');
INSERT INTO "main"."Countrys" VALUES (241, 'UZBEKISTAN', '乌兹别克斯坦', 'UZ');
INSERT INTO "main"."Countrys" VALUES (242, 'VANUATU', '瓦努阿图', 'VU');
INSERT INTO "main"."Countrys" VALUES (243, 'VATICAN CITY STATE ', '梵蒂冈', 'VA');
INSERT INTO "main"."Countrys" VALUES (244, 'VENEZUELA', '委内瑞拉', 'VE');
INSERT INTO "main"."Countrys" VALUES (245, 'VIET NAM', '越南', 'VN');
INSERT INTO "main"."Countrys" VALUES (246, 'VIRGIN ISLANDS ', '美属处女群岛', 'VI');
INSERT INTO "main"."Countrys" VALUES (247, 'WAKE ISLAND', '威克岛', 'XM');
INSERT INTO "main"."Countrys" VALUES (248, 'WALLIS AND FUTUNA ISLANDS', '瓦利斯群岛和富图纳斯岛', 'WF');
INSERT INTO "main"."Countrys" VALUES (249, 'WESTERN SAHARA A', '惜撒哈拉', 'EH');
INSERT INTO "main"."Countrys" VALUES (25, 'BENIN', '贝宁', 'BJ');
INSERT INTO "main"."Countrys" VALUES (250, 'YEMEN ', '也门', 'YE');
INSERT INTO "main"."Countrys" VALUES (251, 'ZAMBIA', '赞比亚', 'ZM');
INSERT INTO "main"."Countrys" VALUES (252, 'ZIMBABWE', '津巴布韦', 'ZW');
INSERT INTO "main"."Countrys" VALUES (254, 'Guernsey', '根西岛GG', 'GG');
INSERT INTO "main"."Countrys" VALUES (255, 'PALAU', '帕劳', 'PLW');
INSERT INTO "main"."Countrys" VALUES (256, 'JERSEY ISLAND', '泽西岛', 'JE');
INSERT INTO "main"."Countrys" VALUES (257, 'Guernsey', '根西岛', 'GCI');
INSERT INTO "main"."Countrys" VALUES (258, 'Crimea', '克里米亚', 'CLM');
INSERT INTO "main"."Countrys" VALUES (259, 'The Republic of Kosovo', '科索沃', 'YK');
INSERT INTO "main"."Countrys" VALUES (26, 'BERMUDA', '百慕达', 'BM');
INSERT INTO "main"."Countrys" VALUES (260, 'REPUBLIC OF SOUTH SUDAN', '南苏丹共和国', 'SSD');
INSERT INTO "main"."Countrys" VALUES (27, 'BHUTAN', '不丹', 'BT');
INSERT INTO "main"."Countrys" VALUES (28, 'BOLIVIA', '玻利维亚', 'BO');
INSERT INTO "main"."Countrys" VALUES (29, 'BOSNIA AND HERZEGOVINA', '波黑', 'BA');
INSERT INTO "main"."Countrys" VALUES (3, 'ALGERIA', '阿尔及利亚', 'DZ');
INSERT INTO "main"."Countrys" VALUES (30, 'BOTSWANA', '博茨瓦纳', 'BW');
INSERT INTO "main"."Countrys" VALUES (31, 'BOUVET ISLAND', '布维岛', 'BV');
INSERT INTO "main"."Countrys" VALUES (32, 'BRAZIL', '巴西', 'BR');
INSERT INTO "main"."Countrys" VALUES (33, 'BRITISH INDIAN OCEAN TERRITORY', '英属印度洋地区', 'IO');
INSERT INTO "main"."Countrys" VALUES (34, 'BRUNEI DARUSSALAM', '文莱达鲁萨兰国', 'BN');
INSERT INTO "main"."Countrys" VALUES (35, 'BULGARIA', '保加利亚', 'BG');
INSERT INTO "main"."Countrys" VALUES (36, 'BURKINA FASO', '布基纳法索', 'BF');
INSERT INTO "main"."Countrys" VALUES (37, 'BURUNDI', '布隆迪', 'BI');
INSERT INTO "main"."Countrys" VALUES (38, 'CAMBODIA', '柬埔寨', 'KH');
INSERT INTO "main"."Countrys" VALUES (39, 'CAMEROON', '喀麦隆', 'CM');
INSERT INTO "main"."Countrys" VALUES (4, 'ANDORRA', '安道尔', 'AD');
INSERT INTO "main"."Countrys" VALUES (40, 'CANADA', '加拿大', 'CA');
INSERT INTO "main"."Countrys" VALUES (41, 'CANARY ISLANDS', '加那利群岛', 'XA');
INSERT INTO "main"."Countrys" VALUES (42, 'CAPE VERDE', '佛得角群岛', 'CV');
INSERT INTO "main"."Countrys" VALUES (43, 'CAROLINE ISLANDS', '加罗林群岛', 'XK');
INSERT INTO "main"."Countrys" VALUES (44, 'CAYMAN ISLANDS', '开曼群岛', 'KY');
INSERT INTO "main"."Countrys" VALUES (45, 'CENTRAL AFRICAN REPUBLIC', '中非共和国', 'CF');
INSERT INTO "main"."Countrys" VALUES (46, 'CHAD', '乍得', 'TD');
INSERT INTO "main"."Countrys" VALUES (47, 'CHANNEL ISLANDS', '海峡群岛', 'XC');
INSERT INTO "main"."Countrys" VALUES (48, 'CHILE', '智利', 'CL');
INSERT INTO "main"."Countrys" VALUES (49, 'CHINA', '中国', 'CN');
INSERT INTO "main"."Countrys" VALUES (5, 'ANGOLA', '安哥拉', 'AO');
INSERT INTO "main"."Countrys" VALUES (50, 'CHRISTMAS ISLAND', '圣诞岛', 'CX');
INSERT INTO "main"."Countrys" VALUES (51, 'COCOS ISLANDS', '科科斯群岛', 'CC');
INSERT INTO "main"."Countrys" VALUES (52, 'COLOMBIA', '哥伦比亚', 'CO');
INSERT INTO "main"."Countrys" VALUES (53, 'COMOROS', '科摩罗', 'KM');
INSERT INTO "main"."Countrys" VALUES (54, 'CONGO ', '刚果民主共和国', 'CD');
INSERT INTO "main"."Countrys" VALUES (55, 'CONGO ', '刚果', 'CG');
INSERT INTO "main"."Countrys" VALUES (56, 'COOK ISLANDS', '库克群岛', 'CK');
INSERT INTO "main"."Countrys" VALUES (57, 'CORSICA', '科西嘉岛', 'XF');
INSERT INTO "main"."Countrys" VALUES (58, 'COSTA RICA', '哥斯达黎加', 'CR');
INSERT INTO "main"."Countrys" VALUES (59, 'COTE D IVOIRE', '科特迪瓦', 'CI');
INSERT INTO "main"."Countrys" VALUES (6, 'ANGUILLA', '安圭拉岛', 'AI');
INSERT INTO "main"."Countrys" VALUES (60, 'CROATIA', '克罗地亚', 'HR');
INSERT INTO "main"."Countrys" VALUES (61, 'CUBA', '古巴', 'CU');
INSERT INTO "main"."Countrys" VALUES (62, 'CYPRUS', '塞浦路斯', 'CY');
INSERT INTO "main"."Countrys" VALUES (63, 'CZECH REPUBLIC', '捷克', 'CZ');
INSERT INTO "main"."Countrys" VALUES (64, 'DENMARK', '丹麦', 'DK');
INSERT INTO "main"."Countrys" VALUES (65, 'DJIBOUTI', '吉布提', 'DJ');
INSERT INTO "main"."Countrys" VALUES (66, 'DOMINICA', '多米尼加岛', 'DM');
INSERT INTO "main"."Countrys" VALUES (67, 'DOMINICAN REPUBLIC', '多米尼加共和国', 'DO');
INSERT INTO "main"."Countrys" VALUES (68, 'EAST TIMOR A', '东帝汶', 'TP');
INSERT INTO "main"."Countrys" VALUES (69, 'ECUADOR', '厄瓜多尔', 'EC');
INSERT INTO "main"."Countrys" VALUES (7, 'ANTARCTICA', '南极洲', 'AQ');
INSERT INTO "main"."Countrys" VALUES (70, 'EGYPT', '埃及', 'EG');
INSERT INTO "main"."Countrys" VALUES (71, 'EL SALVADOR', '萨尔瓦多', 'SV');
INSERT INTO "main"."Countrys" VALUES (72, 'EQUATORIAL GUINEA', '赤道几内亚', 'GQ');
INSERT INTO "main"."Countrys" VALUES (73, 'ERITREA', '厄立特里亚', 'ER');
INSERT INTO "main"."Countrys" VALUES (74, 'ESTONIA', '爱沙尼亚', 'EE');
INSERT INTO "main"."Countrys" VALUES (75, 'ETHIOPIA', '埃塞俄比亚', 'ET');
INSERT INTO "main"."Countrys" VALUES (76, 'FALKLAND ISLAND', '福克兰群岛', 'FK');
INSERT INTO "main"."Countrys" VALUES (77, 'FAROE ISLANDS', '法罗群岛', 'FO');
INSERT INTO "main"."Countrys" VALUES (78, 'FIJI', '斐济', 'FJ');
INSERT INTO "main"."Countrys" VALUES (79, 'FINLAND', '芬兰', 'FI');
INSERT INTO "main"."Countrys" VALUES (8, 'ANTIGUA AND BARBUDA', '安提瓜及巴布达', 'AG');
INSERT INTO "main"."Countrys" VALUES (80, 'FRANCE', '法国', 'FR');
INSERT INTO "main"."Countrys" VALUES (81, 'FRANCE METROPOLITAN', '法属美特罗波利坦', 'FX');
INSERT INTO "main"."Countrys" VALUES (82, 'FRENCH GUIANA', '法属圭亚那', 'GF');
INSERT INTO "main"."Countrys" VALUES (83, 'FRENCH POLYNESIA', '法属波利尼西亚', 'PF');
INSERT INTO "main"."Countrys" VALUES (84, 'FRENCH SOUTHERN TERRITORIES', '法属南部领土', 'TF');
INSERT INTO "main"."Countrys" VALUES (85, 'GABON', '加蓬', 'GA');
INSERT INTO "main"."Countrys" VALUES (86, 'GAMBIA', '冈比亚', 'GM');
INSERT INTO "main"."Countrys" VALUES (87, 'GAZA AND KHAN YUNIS', '加沙及汗尤尼斯', 'XE');
INSERT INTO "main"."Countrys" VALUES (88, 'GEORGIA', '格鲁吉亚', 'GE');
INSERT INTO "main"."Countrys" VALUES (89, 'GERMANY', '德国', 'DE');
INSERT INTO "main"."Countrys" VALUES (9, 'ARGENTINA', '阿根廷', 'AR');
INSERT INTO "main"."Countrys" VALUES (90, 'GHANA', '加纳', 'GH');
INSERT INTO "main"."Countrys" VALUES (91, 'GIBRALTAR', '直布罗陀', 'GI');
INSERT INTO "main"."Countrys" VALUES (92, 'GREECE', '希腊', 'GR');
INSERT INTO "main"."Countrys" VALUES (93, 'GREENLAND', '格陵兰', 'GL');
INSERT INTO "main"."Countrys" VALUES (94, 'GRENADA', '格林纳达', 'GD');
INSERT INTO "main"."Countrys" VALUES (95, 'GUADELOUPE', '瓜德罗普岛', 'GP');
INSERT INTO "main"."Countrys" VALUES (96, 'GUAM', '关岛', 'GU');
INSERT INTO "main"."Countrys" VALUES (97, 'GUATEMALA', '危地马拉', 'GT');
INSERT INTO "main"."Countrys" VALUES (98, 'GUINEA', '新几内亚', 'GN');
INSERT INTO "main"."Countrys" VALUES (99, 'GUINEA-BISSAU', '几内亚比绍', 'GW');
PRAGMA foreign_keys = ON;
