/*
Navicat SQLite Data Transfer

Source Server         : mai
Source Server Version : 31202
Source Host           : :0

Target Server Type    : SQLite
Target Server Version : 31202
File Encoding         : 65001

Date: 2016-07-12 11:57:51
*/

PRAGMA foreign_keys = OFF;

-- ----------------------------
-- Table structure for Posttypes
-- ----------------------------
DROP TABLE IF EXISTS "main"."Posttypes";
CREATE TABLE [Posttypes] (
    [PostID] text PRIMARY KEY NOT NULL,
    [CnPostName] text NOT NULL,
    [EnPostCode] text NOT NULL
);

-- ----------------------------
-- Records of Posttypes
-- ----------------------------
INSERT INTO "main"."Posttypes" VALUES ('001', 'priority air mail', 'PRAM');
INSERT INTO "main"."Posttypes" VALUES ('06', '香港小包平邮', 'HKAM');
INSERT INTO "main"."Posttypes" VALUES ('07', '香港小包挂号', 'HKRAM');
INSERT INTO "main"."Posttypes" VALUES (10, '香港航空大包', 'HKAP');
INSERT INTO "main"."Posttypes" VALUES (100, '英国仓法国邮政', 'FPAM');
INSERT INTO "main"."Posttypes" VALUES (101, 'Royal Mail Suface Mail', 'RMSM');
INSERT INTO "main"."Posttypes" VALUES (102, 'DHL Global Mail(英国仓)', 'DGM');
INSERT INTO "main"."Posttypes" VALUES (103, 'DHL EXPRESS WORLDWIDE', 'UKDHL');
INSERT INTO "main"."Posttypes" VALUES (104, 'France express（Colissimo）', 'FReX');
INSERT INTO "main"."Posttypes" VALUES (105, '英国EUB', 'UKEPACKET');
INSERT INTO "main"."Posttypes" VALUES (106, '中邮北京平邮', 'CNAMBJ');
INSERT INTO "main"."Posttypes" VALUES (107, '中邮北京挂号', 'CNRAMBJ');
INSERT INTO "main"."Posttypes" VALUES (108, '纯电池', 'CDC');
INSERT INTO "main"."Posttypes" VALUES (109, '中国联邦IE', 'CNIPIE');
INSERT INTO "main"."Posttypes" VALUES (11, '长沙EMS', 'CSEMS');
INSERT INTO "main"."Posttypes" VALUES (110, '中国联邦IP', 'CNIPIP');
INSERT INTO "main"."Posttypes" VALUES (111, '中邮泉州平邮', 'CNAMQZ');
INSERT INTO "main"."Posttypes" VALUES (112, '中邮泉州挂号', 'CNRAMQZ');
INSERT INTO "main"."Posttypes" VALUES (113, '新加坡平邮', 'SGAM');
INSERT INTO "main"."Posttypes" VALUES (114, '新加坡挂号', 'SGRAM');
INSERT INTO "main"."Posttypes" VALUES (115, '线下EUB', 'OfflineEPACKET');
INSERT INTO "main"."Posttypes" VALUES (116, 'DHL小包平邮', 'DHLAM');
INSERT INTO "main"."Posttypes" VALUES (117, 'DHL小包挂号', 'DHLAMR');
INSERT INTO "main"."Posttypes" VALUES (118, '飞特全球邮递平邮', 'FGMSN');
INSERT INTO "main"."Posttypes" VALUES (119, '中邮优先平邮', 'CNPM');
INSERT INTO "main"."Posttypes" VALUES (12, '广州EMS', 'GZEMS');
INSERT INTO "main"."Posttypes" VALUES (120, '中邮优先挂号', 'CNPMR');
INSERT INTO "main"."Posttypes" VALUES (121, '英国专线一类挂号', 'RMPR');
INSERT INTO "main"."Posttypes" VALUES (122, 'dhl global mail register(英国仓-挂号)', 'DEFCRAM');
INSERT INTO "main"."Posttypes" VALUES (123, '中国TNT', 'CNTNT');
INSERT INTO "main"."Posttypes" VALUES (124, '晋江线下EUB', 'JJ-EPACKET');
INSERT INTO "main"."Posttypes" VALUES (125, '青岛EUB', 'QDEPACKET');
INSERT INTO "main"."Posttypes" VALUES (126, 'dgm ground service', 'dgmgs');
INSERT INTO "main"."Posttypes" VALUES (127, 'dgm expidite service', 'dgmes');
INSERT INTO "main"."Posttypes" VALUES (128, 'IPA international mail', 'USIPA');
INSERT INTO "main"."Posttypes" VALUES (129, '斐济小包平邮', 'FIPTN');
INSERT INTO "main"."Posttypes" VALUES (13, '香港EMS', 'HKEMS');
INSERT INTO "main"."Posttypes" VALUES (130, '斐济小包挂号', 'FIPTR');
INSERT INTO "main"."Posttypes" VALUES (131, '外围EUB', 'WWEPACKET');
INSERT INTO "main"."Posttypes" VALUES (132, '飞特德国专线挂号', 'FTDEAMR');
INSERT INTO "main"."Posttypes" VALUES (133, '飞特德国专线平邮', 'FTDEAM');
INSERT INTO "main"."Posttypes" VALUES (134, '中邮郑州挂号', 'CNRAMZZ');
INSERT INTO "main"."Posttypes" VALUES (135, '中邮郑州平邮', 'CNAMZZ');
INSERT INTO "main"."Posttypes" VALUES (136, '俄罗斯大包专线', 'CNAPRU');
INSERT INTO "main"."Posttypes" VALUES (137, 'Standard air mail', 'STAM');
INSERT INTO "main"."Posttypes" VALUES (138, 'Standard air mail Register', 'STAMR ');
INSERT INTO "main"."Posttypes" VALUES (139, '香港UPS', 'HKUPS');
INSERT INTO "main"."Posttypes" VALUES (14, '中国UPS', 'CNUPS');
INSERT INTO "main"."Posttypes" VALUES (140, '香港DHL特价A', 'HKDHLTJA');
INSERT INTO "main"."Posttypes" VALUES (141, 'MIX', 'MIX');
INSERT INTO "main"."Posttypes" VALUES (142, '飞特英国小包特惠派送', 'RMXBS');
INSERT INTO "main"."Posttypes" VALUES (143, '新加坡DHL', 'SGDHL');
INSERT INTO "main"."Posttypes" VALUES (144, '飞特新澳宝', 'FTNAP');
INSERT INTO "main"."Posttypes" VALUES (145, 'Flyt UK Standard Parcels', 'FUKPS');
INSERT INTO "main"."Posttypes" VALUES (146, '中邮外围小包平邮', 'CNWWAM');
INSERT INTO "main"."Posttypes" VALUES (147, '中邮外围小包挂号', 'CNWWAMR');
INSERT INTO "main"."Posttypes" VALUES (148, '大陆联邦IP快递袋', 'CNPAK');
INSERT INTO "main"."Posttypes" VALUES (149, '新加坡邮政平邮', 'SGAMP');
INSERT INTO "main"."Posttypes" VALUES (15, 'NNEMS', 'NNEMS');
INSERT INTO "main"."Posttypes" VALUES (150, '新加坡邮政挂号', 'SGAMY');
INSERT INTO "main"."Posttypes" VALUES (151, 'Royal Mail 2nd class-third party', 'RM2NDTHRD');
INSERT INTO "main"."Posttypes" VALUES (152, '中邮东欧专线小包', 'CNAPEUR');
INSERT INTO "main"."Posttypes" VALUES (153, '瑞典邮政(英国仓)', 'SWEDENTPS');
INSERT INTO "main"."Posttypes" VALUES (154, '新加坡EMS', 'SGEMS');
INSERT INTO "main"."Posttypes" VALUES (155, '瑞士小包平邮', 'SWAM');
INSERT INTO "main"."Posttypes" VALUES (156, '瑞士小包挂号', 'SWRAM');
INSERT INTO "main"."Posttypes" VALUES (157, '新加坡瑞典平邮', 'SGSDAM');
INSERT INTO "main"."Posttypes" VALUES (158, '新加坡瑞典挂号', 'SGSDRAM');
INSERT INTO "main"."Posttypes" VALUES (159, '马来西亚邮政平邮', 'MYAMP');
INSERT INTO "main"."Posttypes" VALUES (16, '郑州EMS', 'ZZEMS');
INSERT INTO "main"."Posttypes" VALUES (160, '马来西亚邮政挂号', 'MYAMR');
INSERT INTO "main"."Posttypes" VALUES (161, '飞特邮递平邮特惠', 'THFGMSN');
INSERT INTO "main"."Posttypes" VALUES (162, '飞特邮递挂号特惠', 'THFGMSR');
INSERT INTO "main"."Posttypes" VALUES (163, '俄罗斯专线小包', 'CNAPMRU');
INSERT INTO "main"."Posttypes" VALUES (164, '飞特美国专线', 'FTUSPS');
INSERT INTO "main"."Posttypes" VALUES (165, '中国UPS红单特惠', 'CNUPSRED');
INSERT INTO "main"."Posttypes" VALUES (166, '中国UPS蓝单特惠', 'CNUPSBLUE');
INSERT INTO "main"."Posttypes" VALUES (167, '泰国邮政平邮', 'THAMP');
INSERT INTO "main"."Posttypes" VALUES (168, '泰国邮政挂号', 'THAMR');
INSERT INTO "main"."Posttypes" VALUES (169, 'EBAY UPS', 'EBAYUPS');
INSERT INTO "main"."Posttypes" VALUES (17, 'SHEMS', 'SHEMS');
INSERT INTO "main"."Posttypes" VALUES (170, 'Toll Global Express', 'TollEX');
INSERT INTO "main"."Posttypes" VALUES (171, '国际E特快', 'GJETK');
INSERT INTO "main"."Posttypes" VALUES (172, 'Toll Global Express Bettery', 'TollEXBT');
INSERT INTO "main"."Posttypes" VALUES (173, '香港英国专线平邮', 'HKRMFC');
INSERT INTO "main"."Posttypes" VALUES (174, '香港英国专线二类平邮', 'HKRMSC');
INSERT INTO "main"."Posttypes" VALUES (175, '飞特英国专线Secured mail', 'RMFCR ');
INSERT INTO "main"."Posttypes" VALUES (176, '香港英国专线二类挂号', 'HKRMSCR');
INSERT INTO "main"."Posttypes" VALUES (177, '飞特瑞士专线平邮', 'FTSWFC');
INSERT INTO "main"."Posttypes" VALUES (178, '香港瑞士小包挂号', 'HKSWRAM');
INSERT INTO "main"."Posttypes" VALUES (179, '香港瑞士小包平邮', 'HKSWAM');
INSERT INTO "main"."Posttypes" VALUES (18, '中国DHL', 'CNDHL');
INSERT INTO "main"."Posttypes" VALUES (180, '菲律宾邮政平邮', 'PHAM');
INSERT INTO "main"."Posttypes" VALUES (181, '菲律宾邮政挂号', 'PHRAM');
INSERT INTO "main"."Posttypes" VALUES (182, '德国小包平邮', 'DGAM');
INSERT INTO "main"."Posttypes" VALUES (183, '德国小包挂号', 'DGAMR');
INSERT INTO "main"."Posttypes" VALUES (184, 'GLS欧洲商务包裹', 'GLS');
INSERT INTO "main"."Posttypes" VALUES (185, '俄罗斯线下EUB', 'RUOfflineEPACKET');
INSERT INTO "main"."Posttypes" VALUES (186, '香港英国专线一类挂号', 'HKRMPR');
INSERT INTO "main"."Posttypes" VALUES (187, '立陶宛邮政小包挂号', 'ELTR');
INSERT INTO "main"."Posttypes" VALUES (188, '香港小包平邮敏感渠道', 'HKAMSP');
INSERT INTO "main"."Posttypes" VALUES (189, '瑞典邮政(英国仓)-挂号', 'SWEDENREG');
INSERT INTO "main"."Posttypes" VALUES (19, '飞特美国专线', 'USPS3Days');
INSERT INTO "main"."Posttypes" VALUES (190, '立陶宛邮政小包平邮', 'ELTN');
INSERT INTO "main"."Posttypes" VALUES (191, 'TOLL Global Express vip', 'Toll vip');
INSERT INTO "main"."Posttypes" VALUES (192, '俄罗斯线上EUB', 'RUXXEUB');
INSERT INTO "main"."Posttypes" VALUES (193, '广州EMS（澳大利亚）', 'GZEMSAU');
INSERT INTO "main"."Posttypes" VALUES (194, '瑞典小包平邮', 'SDAM');
INSERT INTO "main"."Posttypes" VALUES (195, '瑞典小包挂号', 'SDRAM');
INSERT INTO "main"."Posttypes" VALUES (196, '退件', 'WT');
INSERT INTO "main"."Posttypes" VALUES (197, '巴西专线小包', 'BZZXR');
INSERT INTO "main"."Posttypes" VALUES (198, 'FBA头程转运', 'FBA');
INSERT INTO "main"."Posttypes" VALUES (199, '荷兰小包平邮', 'NLAM');
INSERT INTO "main"."Posttypes" VALUES (20, 'SZEMS', 'SZEMS');
INSERT INTO "main"."Posttypes" VALUES (200, '荷兰小包挂号', 'NLAMR');
INSERT INTO "main"."Posttypes" VALUES (201, '深圳美国EUB', 'SZEPACKET');
INSERT INTO "main"."Posttypes" VALUES (202, '广州EMS特惠', 'GZEMSTH');
INSERT INTO "main"."Posttypes" VALUES (203, '深圳线下EUB', 'SZEUB');
INSERT INTO "main"."Posttypes" VALUES (204, '晋江加拿大EUB', 'JJ-CAEUB');
INSERT INTO "main"."Posttypes" VALUES (205, '深圳俄罗斯EUB', 'SZRUEUB');
INSERT INTO "main"."Posttypes" VALUES (206, '深圳澳洲EUB', 'SZAUEUB');
INSERT INTO "main"."Posttypes" VALUES (207, '佛山小包挂号', 'CNFSAMR');
INSERT INTO "main"."Posttypes" VALUES (208, '佛山小包平邮', 'CNFSAM');
INSERT INTO "main"."Posttypes" VALUES (209, '香港德国DDP平邮', 'HKDDPAM');
INSERT INTO "main"."Posttypes" VALUES (21, '中邮广州平邮', 'CNAMGZ');
INSERT INTO "main"."Posttypes" VALUES (210, '香港德国DDP挂号', 'HKDDPRAM');
INSERT INTO "main"."Posttypes" VALUES (211, '欧邮宝', 'EU-PACKET');
INSERT INTO "main"."Posttypes" VALUES (212, '香港联邦IE', 'HKIPIE');
INSERT INTO "main"."Posttypes" VALUES (213, '深圳UPS', 'SZUPS');
INSERT INTO "main"."Posttypes" VALUES (214, 'FBA头程转运DHL', 'FDHL');
INSERT INTO "main"."Posttypes" VALUES (215, 'FBA头程转运UPS', 'FUPS');
INSERT INTO "main"."Posttypes" VALUES (216, '俄罗斯小包挂号', 'RUAMR');
INSERT INTO "main"."Posttypes" VALUES (217, '俄罗斯小包平邮', 'RUAM');
INSERT INTO "main"."Posttypes" VALUES (218, '巴西专线小包挂号', 'BRAMR');
INSERT INTO "main"."Posttypes" VALUES (219, '巴西专线小包平邮', 'BRAM');
INSERT INTO "main"."Posttypes" VALUES (22, '中邮广州挂号', 'CNAMGZR');
INSERT INTO "main"."Posttypes" VALUES (220, '广州线上EUB', 'GZ-EPACKET');
INSERT INTO "main"."Posttypes" VALUES (221, '广州线下EUB', 'GZ-OfflineEPACKET');
INSERT INTO "main"."Posttypes" VALUES (222, '杭州线上EUB', 'HZ-EPACKET');
INSERT INTO "main"."Posttypes" VALUES (223, '杭州线下EUB', 'HZ-OfflineEPACKET');
INSERT INTO "main"."Posttypes" VALUES (224, '福州线上EUB', 'FZ-EPACKET');
INSERT INTO "main"."Posttypes" VALUES (225, '福州线下EUB', 'FZ-OfflineEPACKET');
INSERT INTO "main"."Posttypes" VALUES (226, '外围线上EUB', 'WW-EPACKET');
INSERT INTO "main"."Posttypes" VALUES (227, '外围线下EUB', 'WW-OfflineEPACKET');
INSERT INTO "main"."Posttypes" VALUES (228, '美国专线', 'USAM');
INSERT INTO "main"."Posttypes" VALUES (229, '芬兰邮政经济小包', 'FLJJXB');
INSERT INTO "main"."Posttypes" VALUES (23, 'ZHEMS', 'ZHEMS');
INSERT INTO "main"."Posttypes" VALUES (230, '粤邮宝', 'FLTXYB');
INSERT INTO "main"."Posttypes" VALUES (231, '华东UPS', 'HDUPS');
INSERT INTO "main"."Posttypes" VALUES (232, 'PLI-国际小包（英国仓）', 'PLI');
INSERT INTO "main"."Posttypes" VALUES (233, '欧邮宝挂号', 'EU-PACKET-R');
INSERT INTO "main"."Posttypes" VALUES (234, '飞特荷兰专线挂号', 'NLFC-R');
INSERT INTO "main"."Posttypes" VALUES (235, '空运专线', 'EXPRESS');
INSERT INTO "main"."Posttypes" VALUES (236, 'Wish-Epacket', 'Wish-EUB');
INSERT INTO "main"."Posttypes" VALUES (237, 'standard air mail DE', 'STAMRDE');
INSERT INTO "main"."Posttypes" VALUES (238, 'Standard air mail Register DE', 'STAMRDE');
INSERT INTO "main"."Posttypes" VALUES (239, '欧洲TNT', 'EUTNT');
INSERT INTO "main"."Posttypes" VALUES (24, '广州邮政平邮', 'GZAM');
INSERT INTO "main"."Posttypes" VALUES (240, '香港德国专线挂号', 'DEAM-R');
INSERT INTO "main"."Posttypes" VALUES (241, 'UK MAIL大包', 'UK MAIL');
INSERT INTO "main"."Posttypes" VALUES (242, 'B2C EUROP 平邮', 'B2C EUROP');
INSERT INTO "main"."Posttypes" VALUES (243, 'B2C英国挂号', 'B2C');
INSERT INTO "main"."Posttypes" VALUES (244, '日本FBA', 'JP-FBA');
INSERT INTO "main"."Posttypes" VALUES (245, '捷克小包挂号', 'CZAMR');
INSERT INTO "main"."Posttypes" VALUES (246, '捷克小包平邮', 'CZAM');
INSERT INTO "main"."Posttypes" VALUES (247, '中港专线', 'CN-HK');
INSERT INTO "main"."Posttypes" VALUES (248, 'WISH邮', 'wishY');
INSERT INTO "main"."Posttypes" VALUES (249, '老挝小包挂号', 'LWAMR');
INSERT INTO "main"."Posttypes" VALUES (25, '广州邮政挂号', 'GZRAM');
INSERT INTO "main"."Posttypes" VALUES (250, '老挝小包平邮', 'LWAM');
INSERT INTO "main"."Posttypes" VALUES (251, '独轮车专线', 'FTDLC');
INSERT INTO "main"."Posttypes" VALUES (252, 'DGM US intel ', 'DGMUI');
INSERT INTO "main"."Posttypes" VALUES (253, '马来西亚专线', 'MYPR');
INSERT INTO "main"."Posttypes" VALUES (254, 'DGM US intel PKT', 'DGMUI PKT');
INSERT INTO "main"."Posttypes" VALUES (255, 'DGM US intel PLY', 'DGMUI PLY');
INSERT INTO "main"."Posttypes" VALUES (256, '样品订单', 'YPD');
INSERT INTO "main"."Posttypes" VALUES (257, '样品订单', 'YPD');
INSERT INTO "main"."Posttypes" VALUES (258, '欧洲小包平邮', 'EUAM');
INSERT INTO "main"."Posttypes" VALUES (259, '飞特荷兰专线挂号(英仓）', 'NLFCUK-R');
INSERT INTO "main"."Posttypes" VALUES (26, '珠三角EMS', 'ZSJEMS');
INSERT INTO "main"."Posttypes" VALUES (260, 'wish转运', 'CKY');
INSERT INTO "main"."Posttypes" VALUES (261, 'LGS专线快递', 'LGSZX');
INSERT INTO "main"."Posttypes" VALUES (262, '中国邮政平常小包+', 'CNAM+');
INSERT INTO "main"."Posttypes" VALUES (263, '中俄快递SPSR', 'SPSR');
INSERT INTO "main"."Posttypes" VALUES (264, '香港DHL小包平邮', 'HKDHLAM');
INSERT INTO "main"."Posttypes" VALUES (265, '香港DHL小包挂号', 'HKDHLAMR');
INSERT INTO "main"."Posttypes" VALUES (266, '日本黑猫专线', 'JPAMR');
INSERT INTO "main"."Posttypes" VALUES (267, '欧洲FBA', 'OZFBA');
INSERT INTO "main"."Posttypes" VALUES (268, '飞特巴西专线', 'BZFC');
INSERT INTO "main"."Posttypes" VALUES (269, '美仓FBA转运', 'USFBA');
INSERT INTO "main"."Posttypes" VALUES (27, '南宁EMS', 'NNEMS');
INSERT INTO "main"."Posttypes" VALUES (270, '亚马逊FBA空运', 'UKFBA');
INSERT INTO "main"."Posttypes" VALUES (271, '飞特乌克兰专线挂号', 'FTUAFCR');
INSERT INTO "main"."Posttypes" VALUES (272, '乌克兰专线', 'UAFC');
INSERT INTO "main"."Posttypes" VALUES (273, '飞特乌克兰专线平邮', 'FTUAFC');
INSERT INTO "main"."Posttypes" VALUES (274, '无忧物流（普货）', 'WYWL(PH)');
INSERT INTO "main"."Posttypes" VALUES (275, '无忧物流（带电）', 'WYWL(DD)');
INSERT INTO "main"."Posttypes" VALUES (276, 'DHL特价', 'DHLTJ');
INSERT INTO "main"."Posttypes" VALUES (277, '2号France Express(colissimo)', 'FReX-2');
INSERT INTO "main"."Posttypes" VALUES (278, '2号DHL Global Mail(英国仓)', 'DGM-2');
INSERT INTO "main"."Posttypes" VALUES (279, '2号DHL Global Mail register(英国仓)-挂号', 'DEFCRAM-2');
INSERT INTO "main"."Posttypes" VALUES (28, 'USPS First Class', 'USFC');
INSERT INTO "main"."Posttypes" VALUES (280, '2号英国仓法国专线', 'FRDM-2');
INSERT INTO "main"."Posttypes" VALUES (281, '2号France Post Air mail', 'FRAM-2');
INSERT INTO "main"."Posttypes" VALUES (282, '2号B2C Europe 平邮', 'B2C Europe-2');
INSERT INTO "main"."Posttypes" VALUES (283, '2号B2C英国挂号', 'B2C-2');
INSERT INTO "main"."Posttypes" VALUES (284, '香港美国专线', 'HKUSAM');
INSERT INTO "main"."Posttypes" VALUES (285, '土耳其小包平邮', 'TRAM');
INSERT INTO "main"."Posttypes" VALUES (286, '土耳其小包挂号', 'TRAMR');
INSERT INTO "main"."Posttypes" VALUES (287, '加拿大专线', 'CAFC');
INSERT INTO "main"."Posttypes" VALUES (288, '日本佐川专线', 'JPZCR');
INSERT INTO "main"."Posttypes" VALUES (289, '捷克小包挂号(捷克仓)', 'CZAMR-CZ');
INSERT INTO "main"."Posttypes" VALUES (29, 'USPS Parcel Post', 'USPP');
INSERT INTO "main"."Posttypes" VALUES (291, '德国专线快递(捷克仓)', 'DEEX-CZ');
INSERT INTO "main"."Posttypes" VALUES (292, '德国专线小包(捷克仓)', 'DEAM-CZ');
INSERT INTO "main"."Posttypes" VALUES (293, '欧洲快递(捷克仓)', 'EUREX-CZ');
INSERT INTO "main"."Posttypes" VALUES (294, '捷克小包平邮(捷克仓)', 'CZAM-CZ');
INSERT INTO "main"."Posttypes" VALUES (295, '荷兰小包挂号+', 'NLAMR+');
INSERT INTO "main"."Posttypes" VALUES (296, '荷兰小包平邮+', 'NLAM+');
INSERT INTO "main"."Posttypes" VALUES (297, '马邮小包挂号+', 'MYAMR+');
INSERT INTO "main"."Posttypes" VALUES (298, '马邮小包平邮+', 'MYAM+');
INSERT INTO "main"."Posttypes" VALUES (299, '新加坡DHLB', 'SGDHL-B');
INSERT INTO "main"."Posttypes" VALUES (30, 'USPS Priority Mail', 'USPM');
INSERT INTO "main"."Posttypes" VALUES (300, 'FBA美国空运专线', 'FBAKY');
INSERT INTO "main"."Posttypes" VALUES (301, '香港DHL促销', 'HKDHLCX');
INSERT INTO "main"."Posttypes" VALUES (302, 'test-0530', 'test-0530');
INSERT INTO "main"."Posttypes" VALUES (31, 'USPS Express mail', 'USEM');
INSERT INTO "main"."Posttypes" VALUES (32, 'USPS First Class Mail International', 'USFCI');
INSERT INTO "main"."Posttypes" VALUES (33, 'USPS Priority Mail International', 'USPMI');
INSERT INTO "main"."Posttypes" VALUES (34, 'USPS Express Mail International', 'USEMI');
INSERT INTO "main"."Posttypes" VALUES (35, '香港DHL', 'HKDHL');
INSERT INTO "main"."Posttypes" VALUES (36, '飞特英国专线挂号', 'RMFCR');
INSERT INTO "main"."Posttypes" VALUES (37, '飞特英国专线平邮', 'RMFC');
INSERT INTO "main"."Posttypes" VALUES (38, '飞特英国专线二类挂号', 'RMSCR');
INSERT INTO "main"."Posttypes" VALUES (39, '飞特英国专线二类平邮', 'RMSC');
INSERT INTO "main"."Posttypes" VALUES (40, '香港航空大包平邮', 'HKRAP');
INSERT INTO "main"."Posttypes" VALUES (41, '美国E邮宝', 'EPACKET');
INSERT INTO "main"."Posttypes" VALUES (42, 'FedEx Ground', 'UPS Ground');
INSERT INTO "main"."Posttypes" VALUES (43, '中国邮政特惠封', 'CPDL');
INSERT INTO "main"."Posttypes" VALUES (44, '中美转运', 'USCT');
INSERT INTO "main"."Posttypes" VALUES (45, '中邮省内挂号', 'CNGDRAM');
INSERT INTO "main"."Posttypes" VALUES (46, '中国邮政东莞平邮', 'CNAMDG');
INSERT INTO "main"."Posttypes" VALUES (47, '香港小包一级挂号', 'HKFCRAM');
INSERT INTO "main"."Posttypes" VALUES (48, '圆通快递(淘宝使用)', 'YTO');
INSERT INTO "main"."Posttypes" VALUES (49, '国内EMS(淘宝使用)', 'EMS');
INSERT INTO "main"."Posttypes" VALUES (50, '韵达快递(淘宝使用)', 'YUNDA');
INSERT INTO "main"."Posttypes" VALUES (51, '申通快递(淘宝使用)', 'STO');
INSERT INTO "main"."Posttypes" VALUES (52, '顺风快递(淘宝使用)', 'SF');
INSERT INTO "main"."Posttypes" VALUES (53, '中通快递(淘宝使用)', 'ZTO');
INSERT INTO "main"."Posttypes" VALUES (54, '德国专线挂号', 'DEAMR');
INSERT INTO "main"."Posttypes" VALUES (55, '香港德国专线平邮', 'DEAM');
INSERT INTO "main"."Posttypes" VALUES (56, '标准平邮', 'SDAM');
INSERT INTO "main"."Posttypes" VALUES (57, '标准挂号', 'SDAMR');
INSERT INTO "main"."Posttypes" VALUES (58, '标准快递', 'SDEXPRESS');
INSERT INTO "main"."Posttypes" VALUES (59, '国内E邮宝(淘宝使用)', '国内E邮宝(淘宝使用)');
INSERT INTO "main"."Posttypes" VALUES (60, 'USPS Expedite Service', 'USES');
INSERT INTO "main"."Posttypes" VALUES (61, '飞特全球速递专线', 'FGEX');
INSERT INTO "main"."Posttypes" VALUES (62, '中国FEDEX', 'CNFEDEX');
INSERT INTO "main"."Posttypes" VALUES (63, '中邮深圳平邮', 'CNAMSZ');
INSERT INTO "main"."Posttypes" VALUES (64, '中邮深圳挂号', 'CNRAMSZ');
INSERT INTO "main"."Posttypes" VALUES (65, '澳洲E邮宝', 'AUEPACKET');
INSERT INTO "main"."Posttypes" VALUES (66, '飞特法国专线平邮', 'FRAMR');
INSERT INTO "main"."Posttypes" VALUES (67, '中邮杭州平邮', 'CNAMHZ');
INSERT INTO "main"."Posttypes" VALUES (68, '中邮杭州挂号', 'CNAMHZR');
INSERT INTO "main"."Posttypes" VALUES (69, '香港E邮宝', 'HKEPACKET');
INSERT INTO "main"."Posttypes" VALUES (70, '中邮航空大包', 'CNAP');
INSERT INTO "main"."Posttypes" VALUES (71, '中邮SAL大包', 'CNALP');
INSERT INTO "main"."Posttypes" VALUES (72, '中国邮政空运水陆路平邮', 'CNAMSAL');
INSERT INTO "main"."Posttypes" VALUES (73, '中国邮政空运水陆路挂号', 'CNRAMSAL');
INSERT INTO "main"."Posttypes" VALUES (74, '飞特全球邮递挂号', 'FGMSR');
INSERT INTO "main"."Posttypes" VALUES (75, '中邮福州平邮', 'CNAMFZ');
INSERT INTO "main"."Posttypes" VALUES (76, '中邮福州挂号', 'CNRAMFZ');
INSERT INTO "main"."Posttypes" VALUES (77, 'Royal Mail First Class', 'RMFCS');
INSERT INTO "main"."Posttypes" VALUES (78, 'Royal Mail Second Class', 'RMSCS');
INSERT INTO "main"."Posttypes" VALUES (79, 'Royal Mail Second Class Register', 'RMSCRS');
INSERT INTO "main"."Posttypes" VALUES (80, 'Royal Mail Air  Mail', 'RMAM');
INSERT INTO "main"."Posttypes" VALUES (81, 'YOdel 3 days', 'YOdel3');
INSERT INTO "main"."Posttypes" VALUES (82, 'Royal Mail First Class  Register', 'RMFCRS');
INSERT INTO "main"."Posttypes" VALUES (83, 'Royal Mail Air Mail Register', 'RMAMR');
INSERT INTO "main"."Posttypes" VALUES (84, 'DHL Global Mail', 'DHLGM');
INSERT INTO "main"."Posttypes" VALUES (85, 'Roymail Standard Register', 'RMSR');
INSERT INTO "main"."Posttypes" VALUES (86, 'YOdel 2 days', 'YOdel2');
INSERT INTO "main"."Posttypes" VALUES (87, 'YOdel 1 days', 'YOdel1');
INSERT INTO "main"."Posttypes" VALUES (88, '英国仓比利时专线', 'BEDM');
INSERT INTO "main"."Posttypes" VALUES (89, '英国仓荷兰专线', 'NLDM');
INSERT INTO "main"."Posttypes" VALUES (90, '外围EMS', 'WWEMS');
INSERT INTO "main"."Posttypes" VALUES (91, '英国仓法国专线', 'FRDM');
INSERT INTO "main"."Posttypes" VALUES (92, '英国仓德国专线', 'DEDM');
INSERT INTO "main"."Posttypes" VALUES (93, '中邮水陆路大包', 'CNLP');
INSERT INTO "main"."Posttypes" VALUES (94, 'France Post air Mail', 'FRAM');
INSERT INTO "main"."Posttypes" VALUES (95, '中英转运', 'GBCT');
INSERT INTO "main"."Posttypes" VALUES (96, '飞特荷兰专线', 'NLFC');
INSERT INTO "main"."Posttypes" VALUES (97, 'Flyt UK Express', 'FTUKEx');
INSERT INTO "main"."Posttypes" VALUES (98, 'Netherlands air mail', 'UKNLAM');
INSERT INTO "main"."Posttypes" VALUES (99, '英国UPS', 'UKUPS');
PRAGMA foreign_keys = ON;
