//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCB.OrderSorting.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LatticeSetting
    {
        public int ID { get; set; }
        public int CabinetId { get; set; }
        public string LatticeId { get; set; }
        public int Status { get; set; }
        public int LEDIndex { get; set; }
        public int GratingIndex { get; set; }
        public int ButtonIndex { get; set; }
        public string IsEnable { get; set; }
    }
}
