//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCB.OrderSorting.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OldPackingLog
    {
        public string ID { get; set; }
        public string PackNumber { get; set; }
        public string CabinetId { get; set; }
        public string LatticeId { get; set; }
        public string OrderIds { get; set; }
        public string PostTypeIds { get; set; }
        public string PostTypeNames { get; set; }
        public string CountryIds { get; set; }
        public string CountryNames { get; set; }
        public int OrderQty { get; set; }
        public int OperationType { get; set; }
        public System.DateTime OperationTime { get; set; }
        public decimal Weight { get; set; }
        public string UserName { get; set; }
        public int UserId { get; set; }
    }
}
