//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCB.OrderSorting.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderSortingLog
    {
        public string ID { get; set; }
        public string OrderId { get; set; }
        public string TargetCabinetId { get; set; }
        public string TargetLatticeId { get; set; }
        public string ResultCabinetId { get; set; }
        public string ResultLatticeId { get; set; }
        public decimal Weight { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public int Status { get; set; }
        public int OperationType { get; set; }
        public System.DateTime OperationTime { get; set; }
    }
}
