//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCB.OrderSorting.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfo
    {
        public string OrderId { get; set; }
        public string TraceId { get; set; }
        public string CountryId { get; set; }
        public string CountryName { get; set; }
        public string PostId { get; set; }
        public string PostName { get; set; }
        public string Zip { get; set; }
        public decimal Weight { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
