//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCB.OrderSorting.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolutionPostType
    {
        public string Id { get; set; }
        public string SortingSolutionId { get; set; }
        public int CabinetId { get; set; }
        public int LatticeSettingId { get; set; }
        public string PostTypeId { get; set; }
        public string PostTypeName { get; set; }
    }
}
